microsoft/jacdac

dist/services.json
dist/specconstants.ts
services/bootloader.md
services/control.md
spectool/jdspec.d.ts

Fix for https://github.com/microsoft/jacdac/issues/41

renaming device_class to firmware_identifier

---

dist/services.json
dist/specconstants.sts
dist/specconstants.ts
services/aggregator.md
services/bootloader.md
services/control.md
services/crank.md
services/gamepad.md
services/light.md
services/modelrunner.md
services/motor.md
services/music.md
services/power.md
services/pwmlight.md
services/slider.md
services/tcp.md
spec/specification/service-spec-language.mdx
spectool/jdspec.d.ts
spectool/jdspec.ts

Normalize units used in JACDAC to SenML.

adding list of unit from SenML

---

services/mouse.md
spectool/jdspec.d.ts
spectool/jdspec.ts

Support for HID Mouse drivers.

mouse spec

---

dist/services.json
dist/specconstants.sts
dist/specconstants.ts
services/keyboard.md

keyboard spec

---

dist/services.json
dist/specconstants.sts
dist/specconstants.ts
services/codalmessagebus.md

A dedicated spec for codal event bus messages
* should we reserve ranges of message?
* should we specialize this to the microbit?

Codal message bus

---

.github/workflows/build.yml
spec/reference/sws-protocol.mdx

fixing path to images

---

spec/reference/jacdac-protocol.mdx
spec/reference/sws-protocol.mdx

Fix for https://github.com/microsoft/jacdac/issues/59

patch: service_number -> service_index

---

spec/reference.mdx
spec/reference/module-definition.mdx

There will be more needed but this is enough to update the web site.

Rought module to device renamings

---

dist/c/_base.h
dist/c/_sensor.h
dist/services.json
dist/specconstants.sts
dist/specconstants.ts
services/_base.md
services/_sensor.md

const register to specify the preferred default streaming value.

streaming preferred interval

---

dist/services.json
services/_sensor.md
spectool/jdspec.d.ts
spectool/jdspec.ts

Support for https://github.com/microsoft/jacdac/issues/84
```
rw internal streaming_samples: u8 @ streaming_samples
```

internal packets

---

services/distance.md

distance sensor

---

services/ledpixel.md

Renaming generic "light" to "LED pixel"

light -> led pixel

---

services/matrixkeypad.md

Service: Matrix Keypad

---

services/0x1b591bbf.md
services/windspeed.md

Service: Anemometer

---

services/winddirection.md

Service: Wind direction

---

services/lightlevel.md

Service: Light level

---

services/eco2.md

Service: Equivalent CO²

---

services/soilmoisture.md

Service: Soil moisture

---

services/motionsensor.md

Service: Motion sensor

---

services/speechsynthesis.md

This pull request adds a new service definition for JACDAC. Allows a jacdac device to generate speech in the browser for example.

Service: Speech synthesis

---

services/soundlevel.md

Service: Sound level

---

services/color.md

Service: Color

---

services/illuminance.md

Service: Illuminance

---

services/joystick.md

Service: Joystick

---

services/soundplayer.md

Service: Sound player

---

services/waterlevelsensorled.md

Service: Water level sensor LED

---

services/rolemanager.md

Updated role manager

---

services/compass.md

This pull request adds a new service definition for Jacdac.

Service: Compass

---

services/barcodereader.md

This pull request adds a new service definition for Jacdac.
note: dfrobot sells vision accessories that can detect barcodes.

Service: Barcode reader

---

services/soundspectrum.md

This pull request adds a new service definition for Jacdac.

Service: Sound Spectrum

---

services/solenoid.md

This pull request adds a new service definition for Jacdac.

Service: Solenoid

---

services/tests/button.md

Service test: Button

---

services/robotchassis.md

Service: Robot Chassis

---

services/tests/humidity.md

Service test: Humidity

---

services/tests/thermometer.md

Service test: Thermometer

---

services/tests/accelerometer.md

Service test: Accelerometer

---

services/tests/servo.md

Service test: Servo

---

services/control.md

My understand is that we keep this command.

don't deprecate idenfity

---

services/dependablesensor.md

Service: Dependable Sensor

---

services/dimmer.md

Service: Dimmer

---

devices/microsoft/research/jacdacjoystick440344v03.json
devices/microsoft/research/jmaccelerometer30v10.json
devices/microsoft/research/jmambientlight55v01.json
devices/microsoft/research/jmbutton40v02.json
devices/microsoft/research/jmmicrobitshieldlp29v05.json
devices/microsoft/research/jmrgbledgeneric60v01.json
devices/microsoft/research/jmrgbledring37v21.json
devices/microsoft/research/jmtemperaturehumidity18v11.json
dist/devices.json

https://github.com/microsoft/jacdac/issues/881

new designs

---

services/powersupply.md

Service: Power supply

---

services/analogmeasurement.md

Service: Analog Measurement

---

services/acidity.md

acidity service

---

services/dualmotors.md

Service: Dual Motors

---

services/jacscriptcloud.md

Removing twins for now. maybe it can revive later

remove twins

---

devices/keystudio/relaybreakoutboardv10.json
devices/kitronik/accessbitv11.json
devices/kitronik/gamezip64v12.json
devices/kitronik/servolitev10.json
devices/kitronik/stopbitv10.json
devices/microsoft-research/jacdacmicrobitshieldlp29v03.json
devices/microsoft-research/jmbrainesp3248v02.json
devices/microsoft-research/jmbrainesp3248v03.json
devices/microsoft-research/jmbrainf441v02.json
devices/microsoft-research/jmbrainrp204059v01.json
devices/microsoft-research/jmmicrobitshieldlp29v05.json
devices/sparkfun/gamerbitv00.json
devices/yahboom/microbitledv10.json
devices/yahboom/tinybitv13.json
dist/devices.json
spectool/jdspec.d.ts

Align terminology in docs and device registration

Lowhighconsumerprovider

---

services/planarposition.md

Service: Planar position

---

spectool/jdspec.ts

Some helper functions are clashing with the rest of the stack

hide clashing helpers

---

services/devicescriptmanager.md

Adding a semver runtime version.

adding semversion runtime version

---

services/serial.md
spectool/jdspec.ts

Service: Serial

---

services/serial.md

For WebSerial base connection, provide port name

serial connection name

---

devices/forward-education/dialbuttonv10.json
devices/forward-education/fwdeduclimateactionkitgen2v10.json
devices/forward-education/ledlightsv10.json
devices/forward-education/linesensorv10.json
devices/forward-education/moisturesensorv10.json
devices/forward-education/solarsensorv10.json
devices/forward-education/sonarsensorv10.json
devices/forward-education/touchsensorv10.json

Updated FwdEdu productIdentifiers, makeCodeRepo
